sync-repo:
  stage: build
  image: alpine:latest

  # allow us to run pipelines manually online or with a CI schedule
  only:
    - web
    - schedules

  before_script:
    # add the MITRE certificates to the docker image
    - apk update && apk add git openssh-client ca-certificates
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_Root.crt $CRT_R
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-1.crt $CRT_1
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-3.crt $CRT_3
    - update-ca-certificates

    # create a file called push_key that contains the $GITLAB_PUSH_KEY
    - mkdir -p /root/.ssh
    - echo "$GITLAB_PUSH_KEY" > ~/push_key
    - chmod 600 ~/push_key

    # configure git
    - git config --global user.email 'deployer@mitre.org' # Normally this is associated with the $GITLAB_PUSH_KEY
    - git config --global user.name 'inspec-dev Deployer' # Normally this is associated with the $GITLAB_PUSH_KEY

    # add gitlab.mitre.org to known_hosts to avoid "host key verification failed" error
    - touch ~/.ssh/known_hosts
    - echo $GITLAB_KEYSCAN >> ~/.ssh/known_hosts

  script:
    - git clone https://aaronlippold:$(echo $GITHUB_ACCESS_TOKEN)@github.com/aaronlippold/heimdall heimdall >/dev/null 2>/dev/null
    - cd heimdall
    - git remote add github git@gitlab.mitre.org:inspec/heimdall.git
    - ssh-agent sh -c 'ssh-add ~/push_key; git push --tags github master || true' # REMOTE NAME from previous line
deploy:
  stage: deploy 
  image: docker:latest

  before_script:
    # add the MITRE certificates to the docker image
    - apk update && apk add git openssh-client ca-certificates py-pip bash
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_Root.crt $CRT_R
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-1.crt $CRT_1
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-3.crt $CRT_3
    - update-ca-certificates
  
  script:
    # Configuration modification purely for inspec-dev
    # For service behind the MITRE Firewall connecting to gitlab.mitre.org 
    - echo "$SED_PROXY" > sed-script-file
    - grep MITRE_BA_Root dockerfiles/heimdall/Dockerfile || sed -f sed-script-file -i"" dockerfiles/heimdall/Dockerfile
    - cp config/ldap.example.yml config/ldap.yml
    - sed -i"" -e "s#host.yourdomain.com#ldap-user.mitre.org#g" config/ldap.yml
    - sed -i"" -e "s#yourdomain.com#mitre.org#g" config/ldap.yml
    # The following line implies anonymous ldap authentication
    - sed -i"" -e "/admin_/d" config/ldap.yml
    - pip install docker-compose
    - chmod +x docker_build.sh
    - ./docker_build.sh
    - docker-compose up -d
deploy-swarm:
  stage: deploy 
  image: docker:latest
  only:
    - development
  tags:
    - swarm
    - dev

  before_script:
    # add the MITRE certificates to the docker image
    - apk update && apk add git openssh-client ca-certificates py-pip bash
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_Root.crt $CRT_R
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-1.crt $CRT_1
    - wget -O /usr/local/share/ca-certificates/MITRE_BA_NPE_CA-3.crt $CRT_3
    - update-ca-certificates
  
  script:
    # Configuration modification purely for inspec-dev
    # For service behind the MITRE Firewall connecting to gitlab.mitre.org 
    - echo "$SED_PROXY" > sed-script-file
    - grep MITRE_BA_Root dockerfiles/heimdall/Dockerfile.swarm || sed -f sed-script-file -i"" dockerfiles/heimdall/Dockerfile.swarm
    - cp config/ldap.example.yml config/ldap.yml
    - sed -i"" -e "s#host.yourdomain.com#ldap-user.mitre.org#g" config/ldap.yml
    - sed -i"" -e "s#yourdomain.com#mitre.org#g" config/ldap.yml
    # The following line implies anonymous ldap authentication
    - sed -i"" -e "/admin_/d" config/ldap.yml
    - pip install docker-compose
    - chmod +x gen-swarm-secrets.sh
    - ./gen-swarm-secrets.sh
    - docker-compose -f docker-compose.yml.swarm build
    - docker-compose -f docker-compose.yml.swarm push
    - docker stack deploy -c docker-compose.yml.swarm
    - docker-compose -f docker-compose.yml.swarm run web rake db:reset || docker-compose -f docker-compose.yml.swarm run web rake db:migrate
